/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import Clases.cuentaBibliografia;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author aldov
 */
public class ventana_reportePrestamos extends javax.swing.JFrame {

    private static ventana_reportePrestamos instancia;

    public static ventana_reportePrestamos getInstancia() {
        if (instancia == null) {
            instancia = new ventana_reportePrestamos();
        }
        return instancia;
    }

    public ventana_reportePrestamos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reporte_libros = new javax.swing.JButton();
        reporte_librosExistentes = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        reporte_libros.setBackground(new java.awt.Color(51, 51, 255));
        reporte_libros.setForeground(new java.awt.Color(255, 255, 255));
        reporte_libros.setText("Reporte por libros");
        reporte_libros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reporte_librosMouseEntered(evt);
            }
        });
        reporte_libros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporte_librosActionPerformed(evt);
            }
        });

        reporte_librosExistentes.setBackground(new java.awt.Color(51, 51, 255));
        reporte_librosExistentes.setForeground(new java.awt.Color(255, 255, 255));
        reporte_librosExistentes.setText("Reporte de libros existentes");
        reporte_librosExistentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reporte_librosExistentesMouseEntered(evt);
            }
        });
        reporte_librosExistentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporte_librosExistentesActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(51, 51, 255));
        btn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setText("Regresar");
        btn_cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelarMouseEntered(evt);
            }
        });
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(reporte_libros, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(reporte_librosExistentes)
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_cancelar)
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reporte_libros, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reporte_librosExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reporte_librosExistentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporte_librosExistentesActionPerformed
        String reporte = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>Reporte de existencialibros</title>\n"
                + " <style>\n"
                + "        h1, h2{\n"
                + "        color: white;\n"
                + "        text-align: center;\n"
                + "        padding: 5px;\n"
                + "        margin: 5px;\n"
                + "    }\n"
                + "    body{\n"
                + "        background-color: #242a63;\n"
                + "        font-family: Arial;\n"
                + "    }\n"
                + "    \n"
                + "    #main-container{\n"
                + "        margin: 80px auto;\n"
                + "        width: 600px;\n"
                + "    }\n"
                + "    \n"
                + "    table{\n"
                + "        background-color: white;\n"
                + "        text-align: left;\n"
                + "        border-collapse: collapse;\n"
                + "        width: 100%;\n"
                + "    }\n"
                + "    \n"
                + "    th, td{\n"
                + "        padding: 20px;\n"
                + "    }\n"
                + "    \n"
                + "    thead{\n"
                + "        background-color: #246355;\n"
                + "        border-bottom: solid 5px #0F362D;\n"
                + "        color: white;\n"
                + "    }\n"
                + "    \n"
                + "    tr:nth-child(even){\n"
                + "        background-color: #ddd;\n"
                + "    }\n"
                + "    \n"
                + "    tr:hover td{\n"
                + "        background-color: #369681;\n"
                + "        color: white;\n"
                + "    }\n"
                + "    </style>"
                + "</head>\n"
                + "<body>\n"
                + "<h1>REPORTE DE LIBROS PRESTADOS</h1>"
                + "    <div id=\"main-container\">\n"
                + "        <table>\n"
                + "            <tr>\n"
                + "                <th>ISBN/ID</th>\n"
                + "                <th>Tipo</th>\n"
                + "                <th>Autor</th>\n"
                + "                <th>Año Publicación</th>\n"
                + "                <th>Título</th>\n"
                + "                <th>Edición</th>\n"
                + "                <th>Palabras Clave</th>\n"
                + "                <th>Descripción</th>\n"
                + "                <th>Categoría</th>\n"
                + "                <th>Ejemplares</th>\n"
                + "                <th>Temas</th>\n"
                + "                <th>Área</th>\n"
                + "                <th>Palabras clave</th>\n"
                + "                <th>Disponibles</th>\n"
                + "            </tr>\n";
        for (int i = 0; i < prestamoLibros.getInstancia().fila1; i++) {
            reporte += "<tr>";
            for (int j = 0; j < prestamoLibros.getInstancia().columna1; j++) {
                if (prestamoLibros.getInstancia().tablaLibros[i][0] != null) {
                    if (prestamoLibros.getInstancia().tablaLibros[i][j] == null) {
                        prestamoLibros.getInstancia().tablaLibros[i][j] = reporte += "<td>" + "-" + "</td>";
                    } else {
                        reporte += "<td>" + prestamoLibros.getInstancia().tablaLibros[i][j] + "</td>";
                    }

                }
            }
            reporte += "</tr>";
        }
        reporte += "        </table>\n"
                + "    </div>\n"
                + "</body>\n"
                + "</html>";
        File reporteExistenciaLibros = new File("reporteExistenciaLibros_usuarios.html");
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(reporteExistenciaLibros));
            bw.write(reporte);
            bw.close();
            JOptionPane.showMessageDialog(null, "Reporte de existencia de libros realizado correctamente", "Reporte ", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_reporte_librosExistentesActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        ventanaAdministrador.getInstancia().setVisible(true);
        ventana_reportePrestamos.getInstancia().setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void reporte_librosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporte_librosActionPerformed
        String reporte = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "<head>\n"
                + "    <meta charset=\"UTF-8\">\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "    <title>Reporte de libros prestados</title>\n"
                + " <style>\n"
                + "        h1, h2{\n"
                + "        color: white;\n"
                + "        text-align: center;\n"
                + "        padding: 5px;\n"
                + "        margin: 5px;\n"
                + "    }\n"
                + "    body{\n"
                + "        background-color: #242a63;\n"
                + "        font-family: Arial;\n"
                + "    }\n"
                + "    \n"
                + "    #main-container{\n"
                + "        margin: 80px auto;\n"
                + "        width: 600px;\n"
                + "    }\n"
                + "    \n"
                + "    table{\n"
                + "        background-color: white;\n"
                + "        text-align: left;\n"
                + "        border-collapse: collapse;\n"
                + "        width: 100%;\n"
                + "    }\n"
                + "    \n"
                + "    th, td{\n"
                + "        padding: 20px;\n"
                + "    }\n"
                + "    \n"
                + "    thead{\n"
                + "        background-color: #246355;\n"
                + "        border-bottom: solid 5px #0F362D;\n"
                + "        color: white;\n"
                + "    }\n"
                + "    \n"
                + "    tr:nth-child(even){\n"
                + "        background-color: #ddd;\n"
                + "    }\n"
                + "    \n"
                + "    tr:hover td{\n"
                + "        background-color: #369681;\n"
                + "        color: white;\n"
                + "    }\n"
                + "    </style>"
                + "</head>\n"
                + "<body>\n"
                + "<h1>REPORTE DE LIBROS PRESTADOS</h1>"
                + "    <div id=\"main-container\">\n"
                + "        <table>\n"
                + "            <tr>\n"
                + "                <th>ISBN/ID</th>\n"
                + "                <th>Título</th>\n"
                + "                <th>Tipo</th>\n"
                + "            </tr>\n";
        for (int i = 0; i <= cuentaBibliografia.contador; i++) {
            reporte += "<tr>";
            if (cuentaBibliografia.isbn[i] != null) {
                reporte += "<td>" + cuentaBibliografia.isbn[i] + "</td>";
            }
            if (cuentaBibliografia.titulo[i] != null) {
                reporte += "<td>" + cuentaBibliografia.titulo[i] + "</td>";
            }
            if (cuentaBibliografia.tipo[i] != null) {
                reporte += "<td>" + cuentaBibliografia.tipo[i] + "</td>";
            }
            reporte += "</tr>";
        }
        reporte += "        </table>\n"
                + "    </div>\n"
                + "</body>\n"
                + "</html>";
        File reportePrestamos = new File("reportePrestamos.html");
        try {
            BufferedWriter bw = new BufferedWriter(new FileWriter(reportePrestamos));
            bw.write(reporte);
            bw.close();
            JOptionPane.showMessageDialog(null, "Reporte de libros prestados realizado correctamente", "Reporte ", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_reporte_librosActionPerformed

    private void btn_cancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelarMouseEntered
        btn_cancelar.setBackground(Color.white);
        btn_cancelar.setForeground(Color.blue);
        reporte_libros.setBackground(Color.blue);
        reporte_libros.setForeground(Color.white);
        reporte_librosExistentes.setBackground(Color.blue);
        reporte_librosExistentes.setForeground(Color.white);
    }//GEN-LAST:event_btn_cancelarMouseEntered

    private void reporte_librosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporte_librosMouseEntered
        btn_cancelar.setBackground(Color.blue);
        btn_cancelar.setForeground(Color.white);
        reporte_libros.setBackground(Color.white);
        reporte_libros.setForeground(Color.blue);
        reporte_librosExistentes.setBackground(Color.blue);
        reporte_librosExistentes.setForeground(Color.white);
    }//GEN-LAST:event_reporte_librosMouseEntered

    private void reporte_librosExistentesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reporte_librosExistentesMouseEntered
        btn_cancelar.setBackground(Color.blue);
        btn_cancelar.setForeground(Color.white);
        reporte_libros.setBackground(Color.blue);
        reporte_libros.setForeground(Color.white);
        reporte_librosExistentes.setBackground(Color.white);
        reporte_librosExistentes.setForeground(Color.blue);
    }//GEN-LAST:event_reporte_librosExistentesMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana_reportePrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana_reportePrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana_reportePrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana_reportePrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana_reportePrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reporte_libros;
    private javax.swing.JButton reporte_librosExistentes;
    // End of variables declaration//GEN-END:variables
}
